export HCLOUD_TOKEN=
export HCLOUD_IMAGE=ubuntu-20.04
export HCLOUD_LOCATION=nbg1
export HCLOUD_SERVER_TYPE=cx21
export ROOT_SSH_USER=root
export PRIMARY_SSH_USER=ubuntu
export IMAGE_NAME=matrix-base

export ACME_EMAIL=eric@wakoma.co
export TRAEFIK_BASICAUTH_USERS=
export DOMAIN=wakoma.net
export DOMAIN_TRAEFIK=router.meet.${DOMAIN}
export DOMAIN_NETDATA=monitor.meet.${DOMAIN}
export DOMAIN_PROMETHEUS=prometheus.meet.${DOMAIN}
export DOMAIN_MATRIX=matrix.${DOMAIN}
export DOMAIN_ELEMENT=element.${DOMAIN}
export DOMAIN_DIMENSION=dimension.${DOMAIN}
export DOMAIN_JITSI=jitsi.${DOMAIN}

export MATRIX_COTURN_TURN_STATIC_AUTH_SECRET=
export MATRIX_SYNAPSE_MACAROON_SECRET_KEY=
export MATRIX_DIMENSION_ACCESS_TOKEN=
export MATRIX_JITSI_JICOFO_COMPONENT_SECRET=
export MATRIX_JITSI_JICOFO_AUTH_PASSWORD=
export MATRIX_JITSI_JVB_AUTH_PASSWORD=
export MATRIX_JITSI_JIBRI_RECORDER_PASSWORD=
export MATRIX_JITSI_JIBRI_XMPP_PASSWORD=
export MATRIX_POSTGRES_CONNECTION_PASSWORD=

export DOCKER_PGID=$(grep docker /etc/group | cut -d ':' -f 3)
